### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by minisciencegirl** [marbl/harvest#8]
I have been able to run Parsnp on a small subset of draft genomes (~20) in .fasta format. However, when I tried to scale up to a larger number (~200), I get the following error:  
File "<string>", line 656, in <module>
IndexError: string index out of range

Any suggestion on how to fix this error?

Thanks!

**Comment by treangen** [comment]
Hello,

This error is most likely due to an empty or malformatted fasta file. Removing all such files from your genome directory should resolve the error. This should be fixed in the latest release (v1.2). please let me know if you continue to experience this error after removing the files and/or when using v1.2

**Comment by minisciencegirl** [comment]
Hi! 

I am running the latest release (v1.2) and removed all empty fasta files. I am still getting the same error (see below). Thanks!

-->Reading Genome (asm, fasta) files from JM_assembly_201503/..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
Traceback (most recent call last):
  File "<string>", line 656, in <module>
IndexError: string index out of range
